### ISSUE TITLE
LCS violates complexity bound

### ISSUE THREAD

**Issue by o-alexandre-felipe** [gliese1337/fast-myers-diff#1]
Hi @gliese1337 

I appreciate your initiative to write high quality code. I got your package via npm, after I found an unexpected result in the `myers-diff` package. Searching npm I found your package, I tested on my input and it worked, the description was convicing so I decided to try.

It works for all the inputs of sizes less than 3.

The two smallest examples that fail are (using the same representation as you used in your tests).
```javascript
[
  ['a', 'baa', 'a'],
  ['abb', 'b', 'b']
]
```
In order to check I added a variable in the inner loops to count the iterations and break if more than `1000 * Z * Z` were performed in `diff_rect` (9000 for the above examples).

I hope this is a quick fix for you that knows the code.

**Comment by gliese1337** [comment]
Thank you for the bug report! I am investigating.

**Comment by gliese1337** [comment]
@o-alexandre-felipe Turns out there was a bug in the optimization for the special case for one input being a strict suffix of the other. That has been fixed and the updated version published to NPM.
