### ISSUE TITLE
Explain in README the output of calcPatch

### ISSUE THREAD

**Issue by caub** [gliese1337/fast-myers-diff#10]
For example:

```
> [...d.calcPatch('foo!!', 'fo1o')]
[ [ 2, 2, '1', 3 ], [ 3, 5, '', 4 ] ]
```

I guess `[2, 2, '1', 3]` is between 2nd and 2nd char of initial value (remove nothing), insert '1', (what is 3?)

then `[ 3, 5, '', 4 ]` is between 3rd and 5th, insert '' (so remove '!!'), there again what is 4?

Thanks for your project

**Comment by make-github-pseudonymous-again** [comment]
I believe you should not take the last item in consideration. Each tuple in calcPatch is a triple `(deleteStart, deleteEnd, insert)`. The member `insert` is computed [here](https://github.com/gliese1337/fast-myers-diff/blob/a2da289e88e266d55973f2897b91d19ac00c75fd/src/index.ts#L294). For some reason the fourth element is kept in the resulting tuple but I think it should not be taken into account.
